### ISSUE TITLE
Missing libg15render

### ISSUE THREAD

**Issue by cl0h** [Leproide/Linux-G15-Daemon-Logitech-G110-#2]
After following the instructions in the readme I get to the daemon:

`cd g15daemon-1.9.5.3/`
followed by 
 `./configure`

gives:

`
configure: error: ">=libg15render-1.2 (or its devel package) not found.  please install it"`

I don't see any reference to this lib in the source?

**Comment by Leproide** [comment]
Hi!
This repo is a collection of working logitech tools because the binary and source code are very fragmented online, i'm not the programmer and i not have a particular knowledge of the source code, but this error is strange, i never seen this error before now O.o

In any case, i finded the lib here:
https://github.com/berendt/g510s/tree/master/libg15render-1.2

Try to compile this and install :)

**Comment by BenMitnicK** [comment]
Debian Stretch just use this command

sudo apt install libg15render-dev

**Comment by rinaldogiorgetti** [comment]
> Hi! This repo is a collection of working logitech tools because the binary and source code are very fragmented online, i'm not the programmer and i not have a particular knowledge of the source code, but this error is strange, i never seen this error before now O.o
> 
> In any case, i finded the lib here: https://github.com/berendt/g510s/tree/master/libg15render-1.2
> 
> Try to compile this and install :)

I got error when launch "make"

"error: implicit declaration of function ......"
I resolved by insert the below string in pixel.c

#include <unistd.h>
#include <math.h>
#include <stdlib.h>
